// React/restodemo/src/components/ContactComponent.js
import React from 'react';
import { Breadcrumb, BreadcrumbItem,
            Button, Form, FormGroup, Label, Input, Col, FormFeedback } from 'reactstrap';
import { Link } from 'react-router-dom';

class Contact extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            firstname: '',
            lastname: '',
            telnum: '',
            email: '',
            agree: false,
            contactType: 'Tel.',
            message: '',
            touched: {
                firstname: false,
                lastname: false,
                email: false,
                telnum: false
            },

        };

        this.handleSubmit = this.handleSubmit.bind(this);
        this.handleBlur = this.handleBlur.bind(this);
    }

    handleInputChange = (event) => {
        const target = event.target;
        const value = target.type === 'checkbox' ? target.checked : target.value;
        const name = target.name;
    
        this.setState({
          [name]: value
        });
    }

    handleSubmit(event) {
        console.log('Current State is: ' + JSON.stringify(this.state));
        alert('Current State is: ' + JSON.stringify(this.state));
        event.preventDefault();
    }

    handleBlur = (field) => {
        return(
        (event) => {
            this.setState({
                touched: {...this.state.touched, [field]: true}
            });
        })
    }

    validate = (firstname, lastname, telnum, email) => {
        const errors = {
            firstname: '',
            lastname: '',
            telnum: '',
            email: ''
        }

        if(this.state.touched.firstname && firstname.length < 3){
            errors.firstname = 'FirstName Should be >= 3 characters';
        }
        else if(this.state.touched.firstname && firstname.length > 10){
            errors.firstname = 'FirstName Should be <= 10 characters';
        }

        if(this.state.touched.lastname && lastname.length < 3){
            errors.lastname = 'LastName Should be >= 3 characters';
        }
        else if(this.state.touched.lastname && lastname.length > 10){
            errors.lastname = 'LastName Should be <= 10 characters';
        }

        const reg = /^\d+$/;
        if(this.state.touched.telnum && !reg.test(telnum)){
            errors.telnum = 'Tel. Number should contain only numbers';
        }

        if(this.state.touched.email && email.split('').filter(x => x==='@').length !== 1){
            errors.email = 'Email Address is not Valid';
        }

        return errors;

    }

    render(){

        const errors = this.validate(this.state.firstname, this.state.lastname,
            this.state.telnum, this.state.email);

        return(
            <div className="container">
            <div className="row">
                <Breadcrumb>
                    <BreadcrumbItem><Link to="/home">Home</Link></BreadcrumbItem>
                    <BreadcrumbItem active>Contact Us</BreadcrumbItem>
                </Breadcrumb>
                <div className="col-12">
                    <h3>Contact Us</h3>
                    <hr />
                </div>                
            </div>

            <div className="row row-content">
                <div className="col-12">
                    <h3>Location Information</h3>
                </div>

                <div className="col-12 col-sm-4 offset-sm-1">

                        <h5>Our Address</h5>
                        <address>
                        121, Clear Water Bay Road<br />
                        Clear Water Bay, Kowloon<br />
                        HONG KONG<br />
                            <i className="fa fa-phone"></i>: +852 1234 5678<br />
                            <i className="fa fa-fax"></i>: +852 8765 4321<br />
                            <i className="fa fa-envelope"></i>: <a href="mailto:confusion@food.net">confusion@food.net</a>
                        </address>
                </div>

                <div className="col-12 col-sm-6 offset-sm-1">
                    <h5>Map of our Location</h5>
                </div>
                
                <div className="col-12 col-sm-11 offset-sm-1">
                    <div className="btn-group" role="group">
                        <a role="button" className="btn btn-primary" href="tel:+85212345678"><i className="fa fa-phone"></i> Call</a>
                        <a role="button" className="btn btn-info"><i className="fa fa-skype"></i> Skype</a>
                        <a role="button" className="btn btn-success" href="mailto:confusion@food.net"><i className="fa fa-envelope-o"></i> Email</a>
                    </div>
                </div>
            </div>

            <div className="row row-content">

                    <div className="col-12">
                        <h3>Send us your Feedback</h3>
                    </div>

                    <div className="col-12 col-md-9">

                        <Form onSubmit={this.handleSubmit}>

                            <FormGroup row>
                                <Label htmlFor="firstname" md={2}>First Name</Label>
                                <Col md={10}>
                                    <Input type="text" id="firstname" name="firstname" placeholder="First Name"
                                        value={this.state.firstname} onChange={(event) => this.handleInputChange(event)}
                                        valid={errors.firstname === ''} invalid={errors.firstname !== ''}
                                        onBlur={this.handleBlur('firstname')}
                                        />
                                    <FormFeedback>
                                        {errors.firstname}
                                    </FormFeedback>
                                </Col>
                            </FormGroup>

                            <FormGroup row>
                                <Label htmlFor="lastname" md={2}>Last Name</Label>
                                <Col md={10}>
                                    <Input type="text" id="lastname" name="lastname" placeholder="Last Name"
                                        value={this.state.lastname} onChange={(event) => this.handleInputChange(event)}
                                        valid={errors.lastname === ''} invalid={errors.lastname !== ''}
                                        onBlur={this.handleBlur('lastname')}
                                        />
                                    <FormFeedback>
                                        {errors.lastname}
                                    </FormFeedback>
                                </Col>                        
                            </FormGroup>

                            <FormGroup row>
                            <Label htmlFor="telnum" md={2}>Contact Tel.</Label>
                                <Col md={10}>
                                    <Input type="tel" id="telnum" name="telnum" placeholder="Tel. number"
                                        value={this.state.telnum} onChange={(event) => this.handleInputChange(event)}
                                        valid={errors.telnum === ''} invalid={errors.telnum !== ''}
                                        onBlur={this.handleBlur('telnum')}
                                        />
                                    <FormFeedback>
                                        {errors.telnum}
                                    </FormFeedback>
                                </Col>
                            </FormGroup>

                            <FormGroup row>
                                <Label htmlFor="email" md={2}>Email</Label>
                                <Col md={10}>
                                    <Input type="email" id="email" name="email" placeholder="Email"
                                        value={this.state.email} onChange={(event) => this.handleInputChange(event)} 
                                        valid={errors.email === ''} invalid={errors.email !== ''}
                                        onBlur={this.handleBlur('email')}
                                        />
                                    <FormFeedback>
                                        {errors.email}
                                    </FormFeedback>
                                </Col>
                            </FormGroup>

                            <FormGroup row>

                                <Col md={{size: 6, offset: 2}}>
                                    <FormGroup check>
                                        <Label check>
                                            <Input type="checkbox" name="agree" checked={this.state.agree} 
                                                onChange={(event) => this.handleInputChange(event)} /> {' '}
                                            <strong>May we contact you?</strong>
                                        </Label>
                                    </FormGroup>
                                </Col>

                                <Col md={{size: 3, offset: 1}}>
                                    <Input type="select" name="contactType"
                                            value={this.state.contactType}
                                            onChange={(event) => this.handleInputChange(event)}>
                                        <option>Tel.</option>
                                        <option>Email</option>
                                    </Input>
                                </Col>

                            </FormGroup>

                            <FormGroup row>
                                <Label htmlFor="message" md={2}>Your Feedback</Label>
                                <Col md={10}>
                                    <Input type="textarea" id="message" name="message"
                                        rows="12" value={this.state.message}
                                        onChange={(event) => this.handleInputChange(event)}></Input>
                                </Col>
                            </FormGroup>

                            <FormGroup row>
                                <Col md={{size: 10, offset: 2}}>
                                    <Button type="submit" color="primary">
                                        Send Feedback
                                    </Button>
                                </Col>
                            </FormGroup>

                        </Form>
                    </div>
               </div>
               
        </div>
        )
    }
}

export default Contact;

// Angular/restodemo (Most topics covered in this)/src/app/contact/contact.component.ts
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Component, OnInit, ViewChild, Inject } from '@angular/core';

import { FeedbackService } from "../services/feedback.service";
import { Feedback, ContactType } from '../shared/feedback';
import { flyInOut, expand } from '../animations/app.animation';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss'],
  host: {
    '[@flyInOut]': 'true',
    'style': 'display: block;'
  },
  animations: [
    flyInOut(),
    expand()
  ]
})
export class ContactComponent implements OnInit {

  @ViewChild('fform', {static: false}) feedbackFormDirective;

  feedbackForm: FormGroup;
  feedback: Feedback;
  feedbackCopy: Feedback;
  contactType = ContactType;
  errMess: string;
  spinner: boolean;
  showSubmittedDetails: boolean;

  constructor(private fb: FormBuilder,
    private  feedbackService: FeedbackService,
    @Inject('BaseURL') private BaseURL) {
    this.spinner = false;
    this.showSubmittedDetails = false;
    this.createForm();
  }

  formErrors = {
    'firstname': '',
    'lastname': '',
    'telnum': '',
    'email': ''
  };

  validationMessages = {
    'firstname': {
      'required':      'First Name is required.',
      'minlength':     'First Name must be at least 2 characters long.',
      'maxlength':     'FirstName cannot be more than 25 characters long.'
    },
    'lastname': {
      'required':      'Last Name is required.',
      'minlength':     'Last Name must be at least 2 characters long.',
      'maxlength':     'Last Name cannot be more than 25 characters long.'
    },
    'telnum': {
      'required':      'Tel. number is required.',
      'pattern':       'Tel. number must contain only numbers.'
    },
    'email': {
      'required':      'Email is required.',
      'email':         'Email not in valid format.'
    },
  };



  createForm() {
    this.feedbackForm = this.fb.group({
      firstname: ['', [Validators.required,Validators.minLength(2), Validators.maxLength(25) ] ],
      lastname: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(25)] ],
      telnum: ['', [Validators.required, Validators.pattern] ],
      email: ['', [Validators.email]],
      agree: false,
      contacttype: 'None',
      message: ''
    });

    this.feedbackForm.valueChanges
      .subscribe(data => this.onValueChanged(data));

    this.onValueChanged();
  }

  onValueChanged(data?: any) {
    if (!this.feedbackForm) { return; }
    const form = this.feedbackForm;
    for (const field in this.formErrors) {
      if (this.formErrors.hasOwnProperty(field)) {
        // clear previous error message (if any)
        this.formErrors[field] = '';
        const control = form.get(field);
        if (control && control.dirty && !control.valid) {
          const messages = this.validationMessages[field];
          for (const key in control.errors) {
            if (control.errors.hasOwnProperty(key)) {
              this.formErrors[field] += messages[key] + ' ';
            }
          }
        }
      }
    }
  }

  onSubmit() {
    //this.feedback = this.feedbackForm.value;
    this.spinner = true;
    this.feedback = this.feedbackForm.value;
    this.feedbackService.submitFeedback(this.feedback)
      .subscribe((feedback) => {
        this.showSubmittedDetails = true;
        this.spinner = false;
        this.feedback = feedback;
        this.feedbackCopy = feedback;
        
        setTimeout(() => this.showSubmittedDetails = false, 5000);
      },
      (errmess) => {
        this.feedback = null;
        this.feedbackCopy = null;
        this.errMess = <any>errmess;
      })
    //console.log(this.errMess);
    //console.log(this.feedback);
    this.feedbackForm.reset({
      firstname: '',
      lastname: '',
      telnum: '',
      email: '',
      agree: false,
      contacttype: 'None',
      message: ''
    });
    this.feedbackFormDirective.resetForm();
  }

  ngOnInit() {
  }

}

<div class="container"
  fxLayout="column"
  fxLayoutGap="10px">

  <div fxFlex>
    <div>
        <h3>Contact Us</h3>
        <hr>
    </div>
  </div>
  

  <div fxFlex>
    <h3>Location Information</h3> 
    <div fxLayout="column" fxLayout.gt-sm="row">
      <div fxFlex="50" fxFlexOffset="20px">
        <h4>Our Address</h4>
        <address>
          121, Clear Water Bay Road<br>
          Clear Water Bay, Kowloon<br>
          HONG KONG<br>
          <i class="fa fa-phone"></i>: +852 1234 5678<br>
          <i class="fa fa-fax"></i>: +852 8765 4321<br>
          <i class="fa fa-envelope"></i>: 
                <a href="mailto:confusion@food.net">confusion@food.net</a>
        </address>
        <p></p>
        <div>
          <a mat-raised-button href="tel:+85212345678"><i class="fa fa-phone"></i> Call</a>
          <a mat-raised-button><i class="fa fa-skype"></i> Skype</a>
          <a mat-raised-button href="mailto:confusion@food.net"><i class="fa fa-envelope-o"></i> Email</a>
        </div>
        </div>
      <div fxFlex="40">
        <h4>Map of our Location</h4>
      </div>
    </div>
  </div>

  

  <div fxFlex fxFlexOffset="20px" class="form-size">
    <h3>Send us your Feedback</h3>

    <div *ngIf="spinner">
      <h3>Submitting Form</h3>
      <mat-spinner></mat-spinner>
    </div>
    <div fxFlex *ngIf="errMess">
      <h2>Error</h2>
      <h4>{{errMess}}</h4>
    </div>
    
    <div *ngIf="showSubmittedDetails" [@expand]>
      <h3>Your Submission</h3>
      <p>First Name: {{feedback.firstname}}</p>
      <p>Last Name: {{feedback.lastname}}</p>
      <p>Tel. Number: {{feedback.telnum}}</p>
      <p>Email: {{feedback.email}}</p>
      <p>Contact You?: {{feedback.agree}}</p>
      <p>How?: {{feedback.contacttype}}</p>
      <p>Feedback: {{feedback.message}}</p>
    </div>
    
    <form novalidate [formGroup]="feedbackForm" #fform="ngForm" (ngSubmit)="onSubmit()" [hidden]="showSubmittedDetails || spinner" [@expand]>
      <p>
        <mat-form-field class="half-width">
          <input matInput formControlName="firstname" placeholder="First Name" type="text" required>
          <mat-error *ngIf="formErrors.firstname">{{formErrors.firstname}}</mat-error>
        </mat-form-field>
        <mat-form-field class="half-width">
          <input matInput formControlName="lastname" placeholder="Last Name" type="text" required>
          <mat-error *ngIf="formErrors.lastname">{{formErrors.lastname}}</mat-error>
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="half-width">
          <input matInput formControlName="telnum" placeholder="Tel. Number" type="tel" pattern="[0-9]*" required>
          <mat-error *ngIf="formErrors.telnum">{{formErrors.telnum}}</mat-error>
        </mat-form-field>
        <mat-form-field class="half-width">
          <input matInput formControlName="email" placeholder="Email" type="email" email required>
          <mat-error *ngIf="formErrors.email">{{formErrors.email}}</mat-error>
        </mat-form-field>
      </p>
      <table class="form-size">
        <td>
          <mat-slide-toggle formControlName="agree">May we contact you?</mat-slide-toggle>
        </td>
        <td>
          <mat-select placeholder="How?" formControlName="contacttype">
            <mat-option *ngFor="let ctype of contactType" [value]="ctype">
              {{ ctype }}
            </mat-option>
          </mat-select>
        </td>
        </table>
      <p>
        <mat-form-field class="full-width">
          <textarea matInput formControlName="message" placeholder="Your Feedback" rows=12></textarea>
        </mat-form-field>
      </p>
      <button type="submit" mat-button class="background-primary text-floral-white" [disabled]="feedbackForm.invalid">Submit</button>
    </form>
  </div>

</div>
